// Generated by Supabase (supabase gen types typescript).
// Regenerate after any schema change with:
//   npx supabase gen types typescript --project-id ggqgzlqcysmwbpnawfwg > src/types/database.ts
// (or via the Supabase MCP generate_typescript_types tool)
//
// This file is the single source of truth for DB types used by both the
// browser client and the server-side admin client.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      cards: {
        Row: {
          condition: string;
          created_at: string;
          foil: boolean;
          id: number;
          image_url: string | null;
          name: string;
          price_usd: number;
          quantity: number;
          set: string | null;
          type: string | null;
        };
        Insert: {
          condition?: string;
          created_at?: string;
          foil?: boolean;
          id?: never;
          image_url?: string | null;
          name: string;
          price_usd?: number;
          quantity?: number;
          set?: string | null;
          type?: string | null;
        };
        Update: {
          condition?: string;
          created_at?: string;
          foil?: boolean;
          id?: never;
          image_url?: string | null;
          name?: string;
          price_usd?: number;
          quantity?: number;
          set?: string | null;
          type?: string | null;
        };
        Relationships: [];
      };
      newsletter_subscribers: {
        Row: {
          confirmation_expires_at: string | null;
          confirmation_sent_at: string | null;
          confirmation_token_hash: string | null;
          confirmed_at: string | null;
          created_at: string;
          email: string;
          id: string;
          last_bounce_reason: string | null;
          source: string;
          status: Database["public"]["Enums"]["subscriber_status"];
          unsubscribe_token_hash: string | null;
          unsubscribed_at: string | null;
          updated_at: string;
        };
        Insert: {
          confirmation_expires_at?: string | null;
          confirmation_sent_at?: string | null;
          confirmation_token_hash?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
          email: string;
          id?: string;
          last_bounce_reason?: string | null;
          source?: string;
          status?: Database["public"]["Enums"]["subscriber_status"];
          unsubscribe_token_hash?: string | null;
          unsubscribed_at?: string | null;
          updated_at?: string;
        };
        Update: {
          confirmation_expires_at?: string | null;
          confirmation_sent_at?: string | null;
          confirmation_token_hash?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
          email?: string;
          id?: string;
          last_bounce_reason?: string | null;
          source?: string;
          status?: Database["public"]["Enums"]["subscriber_status"];
          unsubscribe_token_hash?: string | null;
          unsubscribed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_deliveries: {
        Row: {
          bounced_at: string | null;
          complained_at: string | null;
          created_at: string;
          delivered_at: string | null;
          email_type: string;
          error_detail: string | null;
          failed_at: string | null;
          id: string;
          idempotency_key: string;
          order_id: string | null;
          resend_email_id: string | null;
          sent_at: string | null;
          status: Database["public"]["Enums"]["email_delivery_status"];
          subscriber_id: string | null;
          suppressed_at: string | null;
          to_email: string;
          updated_at: string;
        };
        Insert: {
          bounced_at?: string | null;
          complained_at?: string | null;
          created_at?: string;
          delivered_at?: string | null;
          email_type: string;
          error_detail?: string | null;
          failed_at?: string | null;
          id?: string;
          idempotency_key: string;
          order_id?: string | null;
          resend_email_id?: string | null;
          sent_at?: string | null;
          status?: Database["public"]["Enums"]["email_delivery_status"];
          subscriber_id?: string | null;
          suppressed_at?: string | null;
          to_email: string;
          updated_at?: string;
        };
        Update: {
          bounced_at?: string | null;
          complained_at?: string | null;
          created_at?: string;
          delivered_at?: string | null;
          email_type?: string;
          error_detail?: string | null;
          failed_at?: string | null;
          id?: string;
          idempotency_key?: string;
          order_id?: string | null;
          resend_email_id?: string | null;
          sent_at?: string | null;
          status?: Database["public"]["Enums"]["email_delivery_status"];
          subscriber_id?: string | null;
          suppressed_at?: string | null;
          to_email?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          amount_due_cents: number;
          cancelled_at: string | null;
          created_at: string;
          delivered_at: string | null;
          discount_cents: number;
          email: string;
          id: string;
          paid_at: string | null;
          payment_provider:
            | Database["public"]["Enums"]["payment_provider"]
            | null;
          payment_reference: string | null;
          payment_status: Database["public"]["Enums"]["payment_status"];
          ship_city: string | null;
          ship_country: string | null;
          ship_line1: string | null;
          ship_line2: string | null;
          ship_postal_code: string | null;
          ship_recipient: string | null;
          ship_state: string | null;
          shipping_cents: number;
          status: Database["public"]["Enums"]["order_status"];
          subtotal_cents: number;
          total_cents: number;
          updated_at: string;
          user_id: string;
        };
        Insert: { [key: string]: unknown };
        Update: { [key: string]: unknown };
        Relationships: [];
      };
      order_items: {
        Row: {
          card_name: string;
          condition: Database["public"]["Enums"]["card_condition"];
          finish: Database["public"]["Enums"]["card_finish"];
          id: string;
          line_total_cents: number;
          order_id: string;
          quantity: number;
          set_name: string | null;
          unit_price_cents: number;
        };
        Insert: { [key: string]: unknown };
        Update: { [key: string]: unknown };
        Relationships: [];
      };
      profiles: {
        Row: {
          first_name: string | null;
          id: string;
          last_name: string | null;
        };
        Insert: { [key: string]: unknown };
        Update: { [key: string]: unknown };
        Relationships: [];
      };
    };
    Views: { [key: string]: never };
    Functions: { [key: string]: never };
    Enums: {
      card_condition: "NM" | "LP" | "MP" | "HP" | "DMG";
      card_finish: "nonfoil" | "foil" | "etched" | "glossy";
      email_delivery_status:
        | "queued"
        | "sent"
        | "delivered"
        | "bounced"
        | "complained"
        | "delivery_delayed"
        | "suppressed"
        | "failed"
        | "canceled";
      order_status:
        | "pending_payment"
        | "paid"
        | "packing"
        | "ready_to_ship"
        | "shipped"
        | "delivered"
        | "cancelled"
        | "refunded";
      payment_provider: "stripe" | "paypal" | "store_credit" | "manual";
      payment_status: "unpaid" | "processing" | "paid" | "refunded" | "failed";
      subscriber_status:
        | "pending"
        | "active"
        | "unsubscribed"
        | "bounced"
        | "complained"
        | "suppressed";
    };
    CompositeTypes: { [key: string]: never };
  };
};
