-- SUPERSEDED — this migration was never applied to production as written.
--
-- Investigation (2026-09-15) found production diverged from this file:
--   * public.card_printings / public.inventory_items / public.inventory_movements
--     DO exist live, but were created by OTHER migrations not present in this
--     repo (e.g. card_printings_cache, inventory_status_movements_rpcs,
--     backfill_cards_into_inventory, full_inventory_reset — see Supabase
--     project migration history), with additional columns this file doesn't
--     define (inventory_items.oracle_id, type_line, colors, creature_types,
--     foil, legacy_mongo_id) and different RLS policy names.
--   * public.scan_sessions / public.card_scans did NOT exist live at all.
--     Production instead had an older, unrelated, unused (0 rows) scanner
--     design: scanner_jobs / scanner_results / scanner_review_queue, backed
--     by a `scanner` storage bucket — from the original 0008_scanner
--     migration — which the admin app's scan repository/UI never actually
--     targets. Those tables are left in place (not dropped) pending a
--     decision on whether anything still depends on them.
--   * public.scan_review_status already existed live with a DIFFERENT,
--     unrelated 4-value set (pending/approved/corrected/rejected) backing
--     scanner_review_queue — this file's 8-value definition would have
--     collided with it.
--
-- Replaying this file's DDL today would fail (policy-name collisions with
-- both the real live policies and the replacement migration below) and would
-- describe a card_printings/inventory_items shape narrower than reality.
--
-- The scan_sessions/card_scans portion — the part actually needed for the
-- real (non-mock) scan repository — was re-applied correctly, under
-- non-colliding names, as 20260915194514_scan_sessions_card_scans.sql.
--
-- The card_printings/inventory_items/inventory_movements portion is already
-- live and does not need to be recreated. A full baseline resync of the
-- ~26 production migrations this repo is still missing (orders, carts,
-- customers, payment events, etc. — none of which this file or the search/
-- scanner work touches) is a separate follow-up: run `supabase link` then
-- `supabase db pull` with the Supabase CLI against this project to generate
-- an accurate baseline from the live schema.
--
-- This file is kept only as a historical record and intentionally contains
-- no executable DDL.
